require('../../bootstrap');
require('./crudTable');
require('./ckeditor');
require('./sidebar');
require('./advisor');
require('./loading');
require('./images');
require('./tabs');
require('./tabs_locale');
require('./uploadImage');
require('./modalImage');
// require('./touch');
